repos:
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Freeze requirements
        entry: .venv/bin/pip freeze > requirements.txt && git add requirements.txt
        language: system
        pass_filenames: false
        stages: [pre-commit]